FROM redis

# COPY ./redis_save/config/ /usr/local/etc/redis/

RUN apt-get -y update
RUN apt-get -y install python3 \
        python3-pip \
        screen \
        procps
RUN pip3 install psycopg2-binary faker numpy cachetools redis

# ENTRYPOINT ["redis-server", "/usr/local/etc/redis/redis.conf"]
